//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntiGit.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Dictionary_it {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Dictionary_it() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AntiGit.Resources.Dictionary_it", typeof(Dictionary_it).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ho corretto l&apos;orologio di sistema!.
        /// </summary>
        public static string ClockFixed {
            get {
                return ResourceManager.GetString("ClockFixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;orologio del computer è.
        /// </summary>
        public static string ComputerClockIs {
            get {
                return ResourceManager.GetString("ComputerClockIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory non trovata.
        /// </summary>
        public static string DirectoryNotFound {
            get {
                return ResourceManager.GetString("DirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore: durante la prima configurazione Git e Source non possono contenere file contemporaneamente: se si desidera sincronizzare questo computer con il Git condiviso, allora Git deve contenere i file e la directory Source deve essere vuota. Se vuoi creare un Git condiviso, allora Git deve essere vuoto e Source deve contenere i file che vuoi condividere..
        /// </summary>
        public static string Error1 {
            get {
                return ResourceManager.GetString("Error1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore: l&apos;applicazione deve essere eseguita in modalità amministratore.
        /// </summary>
        public static string Error2 {
            get {
                return ResourceManager.GetString("Error2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La directory di origine non può essere remota.
        /// </summary>
        public static string Error3 {
            get {
                return ResourceManager.GetString("Error3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File bloccato in modo permanente da un processo.
        /// </summary>
        public static string FileLocked {
            get {
                return ResourceManager.GetString("FileLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOTA: La directory SOURCE è quella con i file da conservare (i tuoi progetti e le tue soluzioni devono essere qui), nella directory TARGET verranno salvati i backup giornalieri, la directory GIT è una directory remota accessibile a tutti coloro che lavorano sul stessi file sorgente, ad esempio, la directory git può corrispondere ad un disco di rete o all&apos;indirizzo di una pen drive collegata al router, in questa directory Context creerà una versione sincronizzata della sorgente in tempo reale..
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Per ripristinare il backup devi copiare la versione desiderata dove preferisci, tramite la riga di comando (il copia e incolla non funziona).
        /// </summary>
        public static string Instruction1 {
            get {
                return ResourceManager.GetString("Instruction1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Si prega di regolare l&apos;orologio di sistema!&quot;.
        /// </summary>
        public static string PleaseAdjustClock {
            get {
                return ResourceManager.GetString("PleaseAdjustClock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fonte non trovata!.
        /// </summary>
        public static string SourceNotFound {
            get {
                return ResourceManager.GetString("SourceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggerimento: si consiglia di impostare il ripristino automatico di Visual Studio su 1 minuto: strumenti-&gt;Opzioni-&gt;Ambiente-Ripristino automatico.
        /// </summary>
        public static string Suggest1 {
            get {
                return ResourceManager.GetString("Suggest1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obiettivo non trovato!.
        /// </summary>
        public static string TargetNotFound {
            get {
                return ResourceManager.GetString("TargetNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;ora corrente del computer non è corretta: è.
        /// </summary>
        public static string TimeIncorrect {
            get {
                return ResourceManager.GetString("TimeIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non è stato possibile controllare l&apos;ora corrente online.
        /// </summary>
        public static string TimeNotCheckedOnline {
            get {
                return ResourceManager.GetString("TimeNotCheckedOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avviso: la sincronizzazione di Git non può essere avviata perché le directory source e git contengono progetti diversi. Controlla le impostazioni!.
        /// </summary>
        public static string Warning1 {
            get {
                return ResourceManager.GetString("Warning1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to È stato eliminato più di un file, per motivi di sicurezza non effettueremo la sincronizzazione se viene eliminato più di un file!.
        /// </summary>
        public static string Warning2 {
            get {
                return ResourceManager.GetString("Warning2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossibile creare collegamenti simbolici.
        /// </summary>
        public static string Warning3 {
            get {
                return ResourceManager.GetString("Warning3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossibile sincronizzare l&apos;orologio.
        /// </summary>
        public static string Warning4 {
            get {
                return ResourceManager.GetString("Warning4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to È possibile eliminare solo le directory vuote.
        /// </summary>
        public static string Warning5 {
            get {
                return ResourceManager.GetString("Warning5", resourceCulture);
            }
        }
    }
}
